# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2faff1353f67b40e868ff6bc61b0ced934fcdf899cbe014bcd0c11cfc6005f48eadc3d6c10999c5adb1a4e0d87dfb516c9443eecd3922e5953d353d2f1c44ba4

test:
  secret_key_base: bdec2149b872acd80be3dae2ee30f9b4c1542d8dcb971d08e411f4e262f46f3e88624d5fabddac8bcbb200bc7b17436d817309695273a4a0ff1bd49ff90da407

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
